#!/bin/bash

ARCH=`lscpu | head -n 1 | awk -F ":" '{print $2}' | tr -d '[:space:]'`
SUDO=`which sudo`
USER=`whoami`
UNZIP=`which unzip`
DIR=$PWD
USER_UID=`id -u $USER`
USER_GID=`id -g $USER`

echo "================================================================="
echo "=== Running Setup Script for Install and Configure PayDayCoin: ==="
echo "=== 1. installing PayDayCoin Daemon"
echo "=== 2. configure Basic PayDayCoin Node"
echo "=== 3. configure Cron Jobs"
if [ "$1" == "masternode" ]; then
echo "=== 4. configure Masternode PayDayCoin Node"
fi
echo "================================================================="
read -p "Are you sure to continue? (yes/no) " answer
if [ "$answer" == "yes" ]; then
	echo "Wait while installing and configuring PayDayCoin Node"
else
	echo "Exit from scripts"
	exit
fi

. $DIR/scripts/utils

config_basic()
{

echo "Initial Basic PayDay daemon config"

PID=$(pidof pdd 2>&1)
if [ "$PID" != "" ]; then
pdd stop > /dev/null 2>&1
wait_pdd_stops
fi

$CMD_SUDO mkdir -p $HOME/.PayDay/
$CMD_SUDO chown -R $USER_UID:$USER_GID $HOME/.PayDay/
echo -en "rpcuser=PayDayrpc\nrpcpassword=" > $HOME/.PayDay/PayDay.conf && echo microtime | md5sum | base64 >> $HOME/.PayDay/PayDay.conf
echo "server=1" >> $HOME/.PayDay/PayDay.conf
echo "daemon=1" >> $HOME/.PayDay/PayDay.conf
$CMD_SUDO chown -R $USER_UID:$USER_GID $HOME/.PayDay/

crontab -l | grep -v "pdd" > /tmp/pdd.cron
echo "@reboot pdd -daemon" >> /tmp/pdd.cron
echo "*/5 * * * *  pdd_sure_run" >> /tmp/pdd.cron
crontab /tmp/pdd.cron
rm -f /tmp/pdd.cron

}

config_masternode()
{

echo "Initial Masternode Configuration"

PID=$(pidof pdd 2>&1)
if [ "$PID" == "" ]; then
pdd > /dev/null 2>&1
wait_pdd_starts
fi

node=`pdd getaddressesbyaccount "" |  grep -oe "[0-9a-zA-Z]*"`
echo Masternode address $node > $HOME/masternode_info.txt
key=`pdd masternode genkey`
pk=`pdd dumpprivkey $node`

echo "Stopping daemon"

pdd stop > /dev/null 2>&1
sleep 1
wait_pdd_stops

echo "Configuring masternode"

CONF=$(cat $HOME/.PayDay/PayDay.conf | grep -v "masternode")
echo "" > $HOME/.PayDay/PayDay.conf
for param in $CONF
do
echo $param >> $HOME/.PayDay/PayDay.conf
done

echo Masternode key $key >> $HOME/masternode_info.txt
echo masternodeprivkey=$key >> $HOME/.PayDay/PayDay.conf
echo masternode=1 >> $HOME/.PayDay/PayDay.conf
echo masternodesoftlock=1 >> $HOME/.PayDay/PayDay.conf

echo "Starting daemon"

echo Masternode wallet private key $pk >> $HOME/masternode_info.txt
echo Your masternode data stored in $HOME/masternode.info.txt
cat $HOME/masternode_info.txt

}

check_root()
{

if [ "$SUDO" == "" ]; then
	echo "To run the script and install PayDayCoin, you need to be installed sudo."
	return 0
else
	return 1
fi

}

if [ "$USER" != "root" ]; then
check_root
	if [ "$?" -eq "1" ]; then
		RUN_AS_ROOT=0
	else
		exit
	fi
	CMD_SUDO='sudo'
else
	CMD_SUDO=''
	RUN_AS_ROOT=1
fi

if [ "$ARCH" = "x86_64" ]; then
	FILE="$PWD/PayDayCoinDaemonLinux_x64.zip"
else
	FILE="$PWD/PayDayCoinDaemonLinux_x86.zip"
fi

if [ "$UNZIP" == "" ]; then
	echo "install unzip"
	$CMD_SUDO apt-get -y install unzip > /dev/null 2>&1
	UNZIP=`which unzip`
fi

cd /tmp/

$UNZIP -o $FILE > /dev/null 2>&1

$CMD_SUDO rm -f /usr/bin/pdd
$CMD_SUDO rm -f /usr/local/bin/pdd
$CMD_SUDO rm -f /usr/local/bin/pdd_sure_run
$CMD_SUDO cp /tmp/pdd /usr/local/bin/pdd
$CMD_SUDO chmod a+x /usr/local/bin/pdd
$CMD_SUDO ln -s /usr/local/bin/pdd /usr/bin/pdd
$CMD_SUDO cp $DIR/scripts/pdd_sure_run /usr/local/bin/
$CMD_SUDO chmod +x /usr/local/bin/pdd_sure_run
$CMD_SUDO mkdir -p /usr/local/lib/pdd/
$CMD_SUDO cp $DIR/scripts/utils /usr/local/lib/pdd/
$CMD_SUDO chmod +x /usr/local/lib/pdd/utils

$CMD_SUDO rm /tmp/pdd

if [ "$1" = "masternode" ]; then
	if [ ! -f "$HOME/.PayDay/PayDay.conf" ]; then
		config_basic
		sleep 1
	fi
	config_masternode
else
	config_basic
	echo "If you want to configure Masternode, run this script again: ./linux_install masternode"
fi

echo "PayDayCoin Node successfull installing. To run - print command: pdd "
