#!/bin/bash

wait_pdd_starts() {

	sleep 5
        while [ -n "$(pdd ping 2>&1)" ]
        do
          echo -n .
          sleep 0.5
        done
	echo
}

wait_pdd_stops() {
	sleep 5
        while [ -z "$(pdd ping 2>&1)" ]
        do
          echo -n .
          sleep 0.5
        done
	echo
}
